# Generated by Django 2.1.5 on 2019-01-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0003_auto_20190128_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='whitelist',
            field=models.ManyToManyField(related_name='users_whitelisted', to='frontpage.User'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='creator',
            field=models.ForeignKey(on_delete=models.SET('[removed]'), related_name='original_poster', to='frontpage.User'),
        ),
    ]
